name: Secrets Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [master]
  push:
    branches: [master]

jobs:
  # Internal PRs from the same repo
  secrets-scan:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ vars.GITLEAKS_NOTIFY_USER_LIST }}
          GITLEAKS_ENABLE_COMMENTS: 'true'
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: 'false'

  # External PRs from forks
  pr-external:
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Checkout base repo (trusted)
      - name: Checkout base repo (trusted)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0

      # Fetch the PR head into ./pr. Treat as data only
      - name: Fetch PR head into ./pr
        run: |
          git fetch origin "pull/${{ github.event.number }}/head:pr"
          git worktree add ./pr pr

      # Install Gitleaks CLI
      - name: Install Gitleaks CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/zricethezav/gitleaks/master/install.sh | bash

      # Run Gitleaks on PR files
      - name: Run Gitleaks scan
        run: |
          ./gitleaks detect --source="./pr" --verbose --redact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ vars.GITLEAKS_NOTIFY_USER_LIST }}
